version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
      - name: status
        tests:
          - accepted_values:
              arguments:
                values: ['completed', 'cancelled', 'pending', 'error']

  - name: mart_customer_revenue
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: max_revenue
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              arguments:
                expression: ">= 0"  
